# Generated by Django 4.2.4 on 2023-09-02 12:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        
    ]
    dependencies = [

    ]
    dependencies = [
    ]

    operations = [
        
    ]

    operations = [
       

    ]

    operations = [

    ]

    

   

    

#
    
