# Generated by Django 4.2.4 on 2023-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteriticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_de_fundação', models.BigIntegerField()),
                ('estadio', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='times',
            name='ano_fundacao',
        ),
        migrations.RemoveField(
            model_name='times',
            name='quant_titulos',
        ),
    ]
