# Generated by Django 4.2.4 on 2023-09-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_caracteriticas_remove_times_ano_fundacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteriticas',
            name='ano_de_fundação',
        ),
    ]
