# Generated by Django 4.2.4 on 2023-09-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_remove_caracteriticas_ano_de_fundação'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadio', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('time', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='times.times')),
            ],
        ),
        migrations.DeleteModel(
            name='Caracteriticas',
        ),
    ]
